version: '3.8'
services:
  book-keeper:
    build: ./book_keeper
    ports:
      - 8080:8080
    depends_on:
      - db
      - stats
  stats:
    build: ./stats
    ports:
      - 8081:8081
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_DB=mydb

volumes:
  postgres_data: